config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'tasks#index'

  get 'tasks', to: 'tasks#index'
  
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task
  
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  
  patch 'tasks/:id', to: 'tasks#update'
  
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    def index
        @tasks = Task.all
    end

    def show
    end

    def new
        @task = Task.new
    end

    def create
        Task.create(task_params)
        redirect_to tasks_path, turbolinks: false
    end

    def edit
    end

    def update
        @task.update(task_params)
        redirect_to task_path, turbolinks: false
    end

    def destroy
        @task.destroy
        redirect_to tasks_path, turbolinks: false
    end

    private
    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end

    def set_task
        @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
<br><br>
  <%= f.label :details %>
  <%= f.text_field :details %>
<br><br>
  <%= f.label :completed  unless @task.new_record? %>
  <%= (f.check_box :completed) unless @task.new_record?%>
<br><br>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Your Tasks</h1>

<% @tasks.each do |task| %>
    <h3><input type="checkbox" <%= task[:completed] ? "checked" : ""  %>><%= link_to task.title, task_path(task)  %></h3>
<% end  %>

<br>
<%= link_to "Create a new Task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Task detail</h1>

<h2><input type="checkbox" <%= @task[:completed] ? "checked" : ""  %>>  <%= @task.title %></h2>
<h3><%= @task.details %></h3>

<br>
<%= link_to "List Tasks", tasks_path %>&nbsp;&nbsp;&nbsp;
<%= link_to "Edit Task", edit_path(@task) %>&nbsp;&nbsp;&nbsp;
<%= link_to "Delete Task", destroy_path(@task), method: :delete, data: { confirm: "Are you sure?" } %>